<a href="https://colab.research.google.com/github/JayasriRayana/Categorising-Flower/blob/main/Categorising_Flower.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing libraries

In [ ]:
import pandas as pd   #importing
import numpy as np 


# Importing and assigning of load_iris

In [ ]:
from sklearn.datasets import load_iris
iris_dataset=load_iris()

#Exlporing each key to know its functionality:

In [ ]:
print(iris_dataset['DESCR'][:193]+"\n....") 
print("target names:{}".format(iris_dataset['target_names']))   #to print species of flower
print("feature names: \n{}".format(iris_dataset['feature_names']))  #for its features like sepals and petals length & width
print("type of data:{}".format(type(iris_dataset['data']))) #type  of the data
print("shape of dtata:{}".format(iris_dataset['data'].shape)) #prints no.of instances and types
print("first five columns of data:\n{}".format(iris_dataset['data'][:5])) 
print("type of target:{}".format(type(iris_dataset['target'])))
print("shape of target:{}".format(iris_dataset['target'].shape))
print("target :\n{}".format(iris_dataset['target']))

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre
....
target names:['setosa' 'versicolor' 'virginica']
feature names: 
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
type of data:<class 'numpy.ndarray'>
shape of dtata:(150, 4)
first five columns of data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
type of target:<class 'numpy.ndarray'>
shape of target:(150,)
target :
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


# Importing train_test_split from sklearn frame work:

In [ ]:
from sklearn.model_selection import train_test_split

# Division of the dataset and arranging randomly:

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(
    iris_dataset['data'],iris_dataset['target'],random_state=0)
print("X_train shape:{}".format(X_train.shape))
print("y_train shape:{}".format(y_train.shape))
print("X_test shape:{}".format(X_train.shape))
print("y_test shape:{}".format(y_train.shape))

X_train shape:(112, 4)
y_train shape:(112,)
X_test shape:(112, 4)
y_test shape:(112,)


# Letting the Machine Learn:

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
Knn=KNeighborsClassifier(n_neighbors=3)
Knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

# To make the predictions:

In [ ]:
x_new=np.array([[5,2.9,1,0.2]])
print("x_new.shape:{}".format(x_new.shape))

x_new.shape:(1, 4)


# To which target does data belong to(which flower):

In [ ]:
prediction=Knn.predict(x_new)
print("Prediction:{}".format(prediction))
print("Prediction target name:{}".format(iris_dataset['target_names'][prediction]))

Prediction:[0]
Prediction target name:['setosa']


# The accurrancy:

In [ ]:
y_pred=Knn.predict(X_test)
print("test set predictions:\n{}".format(y_pred))
print("test set score:{}".format(np.mean(y_pred==y_test)))

test set predictions:
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]
test set score:0.9736842105263158
